name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run Tests
        run: bundle exec rspec

      - name: Run Bundler Audit
        run: bundle exec bundler-audit check --update
